apiVersion: apps/v1
kind: Deployment
metadata:
  name: free-monstro-sre-challenge
  labels:
    app: application
spec:
  replicas: 2  # Adjust the number of replicas based on your scaling needs
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: application
        image: freemonstro/sre-challenge:v0.0.1
        ports:
        - containerPort: 5000  # Specify the port your Flask app is listening on inside the container
        env:
          - name: FLASK_ENV
            value: production  # Set Flask environment variable (optional but recommended)
        resources:
          requests:
            memory: "64Mi"  # Adjust resource requests and limits based on your app's requirements
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz  # Endpoint for liveness probe (optional but recommended)
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readiness  # Endpoint for readiness probe (optional but recommended)
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
